services:
  - type: web
    name: knightbot-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 18.20.2
      - key: TZ
        value: Asia/Jakarta
